#!/bin/bash

OTHER_DEVICE_ID="BBJES6X-JUH4DS6-IPMTFZ3-SNTHVCH-I3A56MM-5J6OIMZ-RA2NNWH-HMPVCQZ"
RemoteDeviceName="hassio002"

usage()
{
        echo "Usage: $prog [id|init|pending|status]"
        echo "Where:"
        echo "    id                    - Show this client ID"
        echo "  init                    - Initialise a new server, must accept on the remote initiator"
        echo "  install <force> user... - Install sincthing on this system, and optionally enable service for user"
        echo "  status                  - display server status including perding folder share requests"
        echo "  pending                 - show pending folder requests"
}

cmd="$1"
shift
prog="$(basename "$0")"

case "$cmd" in
    add)
        FOLDER_ID="$1"
        FOLDER_LABEL="$2"
        FOLDER_PATH="$3"
        if [ -z "$FOLDER_ID" ] || [ -z "$FOLDER_LABEL" ] || [ -z "$FOLDER_PATH" ]
        then
            echo "  FOLDER_ID    = $FOLDER_ID"
            echo "  FOLDER_LABEL = $FOLDER_LABEL"
            echo "  FOLDER_PATH  = $FOLDER_PATH"
            echo "error: must supply id, label an dpath"
            usage
        else
            syncthing cli config folders add --id "$FOLDER_ID" --label "$FOLDER_LABEL" --path "$FOLDER_PATH"
            sleep 3
            syncthing cli config folders "$FOLDER_ID" devices add --device-id "$OTHER_DEVICE_ID"
        fi
        ;;

    id)
        syncthing cli show system | jq .myID
        ;;
    init)
        syncthing cli config devices add --device-id "$OTHER_DEVICE_ID" --name "RemoteDeviceName"
        syncthing cli config devices "$OTHER_DEVICE_ID" introducer set true
        ;;
    install)
        # REF: https://apt.syncthing.net/
        if [ -e /usr/bin/syncthing -a "$1" != "force" ]
        then
            echo "syncthing already installed at /usr/bin/syncthing. Use \"install force\" to force install."
        else
            [ "$1" == force ] && shift

            mkdir -p /etc/apt/keyrings
            rm -f /tmp/syncthing-archive-keyring.gpg
            curl -L -o /tmp/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
            if [ $? == 0 ]
            then
                mv -f /tmp/syncthing-archive-keyring.gpg /etc/apt/keyrings/syncthing-archive-keyring.gpg

                apt modernize-sources

                echo "Types: deb
URIs: http://apt.syncthing.net/
Suites: syncthing
Components: stable-v2
Signed-By: /etc/apt/keyrings/syncthing-archive-keyring.gpg" | \
                    tee /etc/apt/sources.list.d/syncthing.sources

                apt update
                apt install syncthing
            else
                echo "download of syncthing gpg repo key failed"
            fi
        fi

        if [ -e /usr/bin/syncthing ]
        then
            for user in "$@"
            do
                uid="$(id -u "$user" 2> /dev/null)"
                gid="$(id -g "$user" 2> /dev/null)"
                system=""

                case "$user" in
                    syncthing-service)
                        [ -z "$uid" ] || uid="900" # use uid=900 for syncthing-service 
                        system="--system"
                        ;;
                    root)
                        # root needs an override to be able to write to /etc
                        override_d="/etc/systemd/system/syncthing@${user}.service.d"
                        ;;
                esac

                if [ -n "$gid" ]
                then
                    echo "user $user already exists with uid=$uid and gid=$gid."
                else
                    useradd $system -m -o -u $uid -U $user
                fi

                if systemctl is-enabled syncthing@${user}.service &> /dev/null
                then
                    echo "syncthing@${user}.service is already enabled."
                    echo
                    echo "use the following commands to enable more:"
                    echo "  useradd --system -m -u [uid] -U [user_id]"
                    echo "  systemctl enable syncthing@[user_id].service"
                    echo "  systemctl start syncthing@[user_id].service"
                    echo "or"
                    echo "  $prog: install user..."
                else
                    systemctl enable syncthing@${user}.service
                    systemctl start syncthing@${user}.service
                fi

                if [ -n "$override_d" ]
                then
                    echo
                    echo "[Service]
ProtectSystem=true
ReadWritePaths=/etc
" > "$override_d/override.conf"
                    if [ -e "$override_d/override.conf" ]
                    then
                        echo "$override_d: Override file updated."
                    else
                        echo "$override_d: Override file created."
                    fi

                    echo
                    echo "doing systemctl daemon-reload"
                    systemctl daemon-reload
                    echo

                    for folder in /etc /usr /bin /sbin
                    do
                        stignore="${folder}/.stignore"
                        if [ -e "$stignore" ]
                        then
                            echo "$stignore: file exists."
                        else
                            echo '**' > "$stignore"
                            echo "$stignore: file created."
                        fi
                    done
                fi

                echo
            done
        fi
        ;;
    status)
        syncthing cli config devices "$OTHER_DEVICE_ID" dump-json | jq
        ;;
    pending)
        syncthing cli show pending folders
        ;;
    *)
        usage
        ;;
esac

