#!/bin/bash

sha1sum()
{
        if [ $# != 0 ]
        then
                set -- $(/usr/bin/sha1sum "$1")
                echo $1
        fi
}

auto_generated_msg_start()
{
	echo "#
# Auto generated
#   by:  $(/usr/bin/readlink -f "$0")
#
# Please do not edit this file directly
#
"
}

