#!/bin/sh
#
# managed by pfSense system_patches addon
# WARNING: Do not edit this file, your changes will be lost.
#

s="qemu-guest-agent"

# check if this system is running on QEMU hardware
if [ "`/usr/local/sbin/dmidecode -s system-manufacturer`" == "QEMU" ]
then
	# install qemu-guest-agent if needed
	if [ ! -x "/usr/local/etc/rc.d/$s" ]
	then
		/usr/sbin/pkg install -y $s
	fi

	if [ -x "/usr/local/etc/rc.d/$s" ]
	then
	    "/usr/local/etc/rc.d/$s" "$@"
	fi
fi

unset s
