#!/bin/bash

. /usr/local/sbin/local-functions

getssl_dir="/etc/getssl"
prog="/usr/local/sbin/getssl --all --upgrade -w $getssl_dir --keep 40"


log_init "/var/log/getssl/renew.log"

(
	for dom in ${getssl_dir}/*
	do
		[ -e "${dom}/getssl.cfg" ] && echo $prog $(/usr/bin/basename "$dom") 2>&1
	done

)  | (

	hostname="$(/bin/hostname)"
	sucessMsg="No renewals were attempted."
	sucessMsg="certificate is valid for more than "
	mailSubject="${prog##*/} from $hostname"
	sleep="$(($RANDOM % 120))"
	sleep="$(($sleep * 60))"


	while [ "$#" != 0 ]
	do
		[ "$1" == "--no-sleep" ] && sleep="0"
		shift
	done



	log "start cert check: runnng from ${hostname}: $prog"
	log "random sleep for $sleep seconds"

	/bin/sleep $sleep

	while read line
	do
		log "-> $line"
	done

	log "exited with value $?"

	if [ "$(echo -e "$msg" | /bin/fgrep -c "$sucessMsg")" -eq 0 ]
	then
		log "emailing"
		mail -s "$mailSubject" $mailTo <<< "$msg"
	else
		log "not emailing"
		mail -s "$mailSubject" $mailTo <<< "$msg"
	fi
)

exit 0

