#!/bin/bash

. /usr/local/sbin/local-functions

progName="getssl"
prog="/usr/local/sbin/${progName} --all --upgrade"

log_init "/var/log/${progName}/renew.log"

$prog 2>&1 | (

	hostname="$(/bin/hostname)"
	sucessMsg="No renewals were attempted."
	mailSubject="${prog##*/} from $(/bin/hostname)"
	sleep="$(($RANDOM % 120))"
	sleep="$(($sleep * 60))"


	while [ "$#" != 0 ]
	do
		[ "$1" == "--no-sleep" ] && sleep="0"
		shift
	done



	log "start cert check: runnng from ${hostname}: $prog"
	log "random sleep for $sleep seconds"

	/bin/sleep $sleep

	while read line
	do
		log "-> $line"
	done

	log "exited with value $?"

	if [ "$(echo -e "$msg" | /bin/fgrep -c "$sucessMsg")" -eq 0 ]
	then
		log "emailing"
		mail -s "$mailSubject" $mailTo <<< "$msg"
	else
		log "not emailing"
		mail -s "$mailSubject" $mailTo <<< "$msg"
	fi
)

exit 0

