#!/bin/bash

functions=""

[ -e /usr/local/sbin/local-functions ] && functions="/usr/local/sbin/local-functions"
[ -e /opt/git-repo/local/sbin/local-functions ] && functions="/opt/git-repo/local/sbin/local-functions"

if [ -n "$functions" ]
then
	. "$functions"
	mail "$@"
fi

