#!/bin/bash

bw="/usr/local/scripts/sbin/bw"
config="/usr/local/scripts/.git/config"

key="$("$bw" get item github.com)"
key="${key##*\"fine grained token\",\"value\":\"}"
key="${key%%\"*}"

echo "got key=$key"

/usr/bin/sudo /bin/cp "$config" "${config}.bak" &&
    /usr/bin/sed "s,\(^\s*pushurl = https://\).*\(@.*\),\1$key\2,g" < "${config}.bak" | /usr/bin/sudo /bin/tee "$config" &&
/usr/bin/sudo /bin/rm -f "${config}.bak"
