#!/bin/bash

# cron.daily script to update local scripts

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 0 * * * root /usr/local/scripts/install.sh
@reboot root /usr/local/scripts/install.sh
