#!/bin/sh
#
# managed by pfSense system_patches addon
# WARNING: Do not edit this file, your changes will be lost.
#
# REF: https://forum.netgate.com/topic/162083/pfsense-vm-on-proxmox-qemu-agent-installation
#

s="syncthing"

#if [ ! -x "/usr/local/etc/rc.d/$s" ]
#then
#	/usr/sbin/pkg install -y $s
#fi

if [ -x "/usr/local/etc/rc.d/$s" ]
then
    "/usr/local/etc/rc.d/$s" "$@"
fi

unset s
